/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#002113",
        "inverse-primary": "#ffb77d",
        "primary-container": "#b15f00",
        "on-error": "#ffffff",
        "on-secondary-fixed-variant": "#3f465c",
        "on-tertiary-container": "#00311f",
        "surface-bright": "#f7f9fb",
        "tertiary": "#006c49",
        "surface-container-low": "#f2f4f6",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#4edea3",
        "primary-fixed-dim": "#ffb77d",
        "tertiary-container": "#00a572",
        "surface-tint": "#904d00",
        "on-primary-fixed-variant": "#6e3900",
        "on-background": "#191c1e",
        "surface-container-high": "#e6e8ea",
        "surface-variant": "#e0e3e5",
        "on-secondary-container": "#5c647a",
        "secondary-fixed-dim": "#bec6e0",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#eff1f3",
        "inverse-surface": "#2d3133",
        "primary": "#8d4b00",
        "error": "#ba1a1a",
        "surface-dim": "#d8dadc",
        "on-surface": "#191c1e",
        "tertiary-fixed": "#6ffbbe",
        "on-surface-variant": "#554336",
        "surface": "#f7f9fb",
        "secondary-container": "#dae2fd",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "outline": "#887364",
        "secondary-fixed": "#dae2fd",
        "surface-container": "#eceef0",
        "surface-container-highest": "#e0e3e5",
        "secondary": "#565e74",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#131b2e",
        "primary-fixed": "#ffdcc3",
        "on-tertiary-fixed-variant": "#005236",
        "background": "#f7f9fb",
        "on-primary-fixed": "#2f1500",
        "outline-variant": "#dbc2b0",
        "on-primary-container": "#fffbff",
        "on-tertiary": "#ffffff",
        lumo: {
          50: '#FFF7ED',
          100: '#FFEDD5',
          200: '#FED7AA',
          300: '#FDBA74',
          400: '#FB923C',
          500: '#FF5500', // Official LUMO Orange CTA
          600: '#EA580C',
          700: '#C2410C',
          navy: '#0F172A', // Official Blue Bahari / Navy Blue
          navyLight: '#1E293B',
          orange: '#FF5500',
        },
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'Inter', 'sans-serif'],
        mono: ['Space Mono', 'JetBrains Mono', 'monospace'],
        "code-tracking": ["Space Mono", "monospace"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"]
      },
      fontSize: {
        "code-tracking": ["15px", { lineHeight: "20px", letterSpacing: "0.06em", fontWeight: "700" }],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "700" }],
        "display-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "display-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "headline-lg": ["30px", { lineHeight: "38px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "700" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }]
      },
      boxShadow: {
        glass: '0 8px 32px 0 rgba(15, 23, 42, 0.08)',
        card: '0 2px 10px 0 rgba(15, 23, 42, 0.05)',
        glow: '0 0 20px rgba(30, 64, 175, 0.25)',
      },
    },
  },
  plugins: [],
};
